vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        attachments:
            uri_prefix: /uploads/attachments
            upload_destination: '%kernel.project_dir%/public/uploads/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
